### ISSUE TITLE
First Communication

### ISSUE THREAD

**Issue by jstngoulet** [Moodle-teamCSUSM/project-documentation#1]
### Time to commit!
If you have not yet already, commit, or deny, this project by commenting here. If you have committed, please be sure to sign up for the slack team by selecting the related link in the readme file. If you are not interested, please leave a commit here so we may remove your invitation from the repository.

** Note: ** Anyone who has not responded by January 5th will have their access removed.

I would love to have you as part of the team!

**Comment by jstngoulet** [comment]
## Last Call for Ideas!
### Voting Starts Tomorow on slack!

Please submit any further ideas you have for the project. Voting will start on slack tomorrow. If you have not yet done so, please see the slack invite link at the bottom of te README. I look forward to working with you!

**Comment by notjvb** [comment]
I'm interested in this project, however, my time is scarce. I can't really commit to building anything, but I am willing to lend my expertise in a quasi-consultant capacity - if you want my input, I'm happy to lend a hand.

**Comment by jstngoulet** [comment]
No prob @jvb93 . As this is most of our last semester, we aren't going to be too concerned for time, as long as we are all on the same page.

Also, thanks @jvb93 for noting the invite link expired. Please text/email me at jstngoulet@me.com so I can add your email to the team!
